# 1. Sintaxis y espacios en blanco


In [5]:
num_estu  = int(input("Ingresa tu numero de estudiante \n"))
if num_estu != 0:
    print(f"Bienvenido estudiante numero {num_estu}")
else:
    print("Ingresa bien tu numero :v")

Ingresa tu numero de estudiante 
100
Bienvenido estudiante numero 100


# 2. Comentarios

In [6]:
print("Hola")  #esto es un comentario


Hola


# 3. Numeros y operaciones

In [11]:
a = 5 + 8
print(f"La suma de los numeros es: {a} y su formato", type(a))

b = 5 + 2.3
print(f"La suma de los numeros es: {b} y su formato", type(b))

La suma de los numeros es: 13 y su formato <class 'int'>
La suma de los numeros es: 7.3 y su formato <class 'float'>


# 4.Manipulación de cadenas

In [16]:
# crearemos una cadena y la imprimimos
palabra= "Que onda"
print(palabra)

#Ahora encontramos el primer caracter, es decir Q
print(palabra[0])

#El tamaño de la cadena es:
print(len(palabra))

#mas ejemplos
print(palabra.count('Q')) #cuenta las veces que se repite una letra
print(palabra.find('u')) #encuentra la letra
print(palabra.count(' ')) #encuentra los espacios en blanco
print(palabra.title())
print(palabra.upper()) #cambia a mayuculas, minusculas o ambos
print(palabra.lower())
print(palabra + '!! :)') #concatena cadenas
print(':'.join(palabra)) #agrega : entre cada elemento 
print("".join(reversed(palabra))) # Escribe alrevez la cadena

Que onda
Q
8
1
1
1
Que Onda
QUE ONDA
que onda
Que onda!! :)
Q:u:e: :o:n:d:a
adno euQ


# 5.Listas, tuplas y diccionarios


In [19]:
lista_1 = [] #lista vacia
lista_2 = [1,2,3,4]
lista_3 = [1,'jitomate',4,5,6]

#Multiples listas
lista_4 = lista_2 + lista_3
lista_4




#Eliminamos elemtos
lista_4.pop()

'gansito'

In [20]:
#Imprimimos una seccion de la lista
lista_4[0:7]

[1, 2, 3, 4, 1, 'jitomate', 4]

In [ ]:
#Agregamos elementos 
lista_4.append('gansito')
lista_4

In [21]:
#Eliminamos elemtos
lista_4.pop(0)
lista_4

[2, 3, 4, 1, 'jitomate', 4, 5, 6]

In [ ]:
#iterando una lista
for elemento in lista_4:
    print(elemento)

# Tuplas

In [22]:
tupla = [1,2,3,4,5]
tupla[:]

[1, 2, 3, 4, 5]

# Diccionarios 


In [24]:
personas = {'jack' : 123, 'joe' : 234, 'harry'  : 345}
personas['joe']

234

# 6.JSON

In [26]:
import json
x = '{"nombre":"Juan", "apellido":"Gansito", "edad": 25, "ciudad":"CDMX" }'

#leyendo datos

y = json.loads(x)

print("El nombre es: " + y["nombre"] + " " + y["apellido"])

El nombre es: Juan Gansito


# 7.Loops

In [27]:
a = 22
b = 33
c = 100

#ejemplo con if
if a > b:
    print("a es mayor que b")
else:
    print("b es mayor que a")

#ejemplo con if, else, elif
if a > b:
    print("a es mayor que b")
elif a == b:
    print("a es igual a b")
else:
    print("b es mayor que a")
    

b es mayor que a
b es mayor que a


In [33]:
#ciclo while
i = 1
while i < 10:
    print("contador:", i)
    i += 1

print("="*10)

#ejemplo
x = 0
while x < 5:
    x += 1
    if x == 2:
        continue
    print(x)
else:
    print("x ya no es menor a 5")
    

contador: 1
contador: 2
contador: 3
contador: 4
contador: 5
contador: 6
contador: 7
contador: 8
contador: 9
1
3
4
5
x ya no es menor a 5


In [35]:
#ciclo for
frutas = ["naranja", "mango", "naranja","fresa"]
for fruta in frutas:
    print(fruta)
    
print("\n")
print("="*10)

#iteracion range

for z in range(1,2,3):
    print(z)
else:
    print("tarea completada")

naranja
mango
naranja
fresa


1
tarea completada


# Manejo de archivos

In [37]:
#existen 4 metodos diferentes para abrir un archivo
# "r" Read, "a" Append, "w" Write, "x" Create
# y para especificar que tipo de archivo es:
# "t" text, "b" bynari

!echo "Primera linea" > test.txt
!echo "Segunda linea" > tets.txt
!echo "Tercera linea" > test.txt

In [39]:
#Leyendo archivos
file = open('test.txt','r')
print(file.read())
file.close()

print("\n")
print("="*10)
print("\n")

#leyendo los primeros 10 elementos
file = open('test.txt','r')
print(file.read(10))
file.close()

print("\n")
print("="*10)
print("\n")

#leyendo

file = open('test.txt','r')
print(file.readline())
file.close()


Tercera linea





Tercera li




Tercera linea



In [40]:
# creando nuevo archivo
file = open('test2.txt','w')
file.write("Contenido del nuevo archivo")
file.close()

#leyendo el contenido
file = open('test2.txt','r')
print(file.read())
file.close()

Contenido del nuevo archivo


In [ ]:
#actualizando archivo
file = open('test2.txt','r')
file.write("rjrjnrkmemke")
file.close()

#leyendo el contenido 
file = open('test2.txt','r')
print(file.read())
file.close()

In [ ]:
#borrar archivo
import os
archivos = ["test.txt", "test2.txt"]
for elementos in archivos:
    if os.path.exists(elementos):
        os.remove(elementos)
        print(f"archico {elementos} eliminado con exito!")
    else:
        print(f"{elementos} el archivo no existe.")

# 9.Funciones

In [41]:
def funcion():
    print("nueva funcion")

funcion()

nueva funcion


In [42]:
#funcion con parametros

def funcion_para(nombre):
    print(f"El nombre es: {nombre}")

funcion_para("paco")
funcion_para("gaby")
funcion_para("taco")


El nombre es: paco
El nombre es: gaby
El nombre es: taco


In [43]:
#funcion lambda
x = lambda y: y + 100
print(x(15))

print("\n")
print("="*10)
print("\n")

x = lambda a, b: a*b/100
print(x(2,4))

115




0.08


# 10.Trabajando con datetime

In [44]:
import datetime

x = datetime.datetime.now()

print(x)
print(x.year)
print(x.strftime("%A"))
print(x.strftime("%B"))
print(x.strftime("%d"))
print(x.strftime("%H:%M:%S %p"))

2022-09-17 22:02:00.328656
2022
Saturday
September
17
22:02:00 PM


# 11.NumPy

In [45]:
!pip install numpy
import numpy as np

In [49]:
#
a = np.arange(15).reshape(3,5)
b = np.zeros((3,5))
c = np.ones((2,3,4), dtype = np.int16)
d = np.ones((3,5))

In [50]:
a.shape

(3, 5)

In [53]:
len(b)

3

In [52]:
c.ndim

3

In [54]:
a.size

15

In [55]:
b.dtype

dtype('float64')

In [56]:
c.dtype.name

'int16'

In [57]:
c.astype(float)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [58]:
#Operaciones basicas
a = np.arange(15).reshape(3,5)
b = np.zeros((3,5))
c = np.ones((2,3,4), dtype = np.int16)
d = np.ones((3,5))

In [59]:
np.add(a,b)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [60]:
np.subtract(a,b)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [61]:
np.divide(a,d)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [62]:
np.multiply(a,d)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [63]:
np.array_equal(a,b)

False

## Agregando funciones

In [64]:
a = np.arange(15).reshape(3,5)
b = np.zeros((3,5))
c = np.ones((2,3,4), dtype = np.int16)
d = np.ones((3,5))

In [65]:
a.sum()

105

In [66]:
a.min()

0

In [67]:
a.mean()

7.0

In [68]:
a.max(axis=0)

array([10, 11, 12, 13, 14])

In [69]:
np.std(a)

4.320493798938574